entitlements/strictly-audited/admin.txt:
  sha256sum: ef9dda024f42b1773152d9fed6084d06738e989a99a342459b0f2de126ac93d4
  format:
    - txt
  reviews:
    enabled: true
    labels:
      - Periodic Audit
    days: 182
    strategy: manager
    title: Admin access
