<%-
begin
  require_relative "/data/entitlements/lib/entitlements-and-plugins"
rescue Exception
  begin
    require_relative "lib/entitlements-and-plugins"
  rescue Exception
    # We might not have the plugins installed and still want this file to be
    # loaded. Don't raise anything but silently fail.
  end
end
-%>
---
backends:
  dockerized-ldap:
    ldap_binddn: "cn=admin,dc=example,dc=org"
    ldap_bindpw: "admin"
    ldap_uri: "ldaps://127.0.0.1"
    disable_ssl_verification: true
    person_dn_format: uid=%KEY%,ou=People,dc=example,dc=org
    type: ldap
configuration_path: ../
extras:
  ldap_group: {}

groups:
  dummy-ou:
    type: dummy
  dummy-ou-renamed:
    type: dummy
    dir: dummy-ou-special
  entitlements:
    backend: dockerized-ldap
    base: ou=Entitlements,ou=Groups,dc=example,dc=org
  entitlements/strictly-audited:
    backend: dockerized-ldap
    base: ou=strictly-audited,ou=Entitlements,ou=Groups,dc=example,dc=org
    dir: entitlements/strictly-audited
    create_if_missing: true
people:
  ldap:
    type: ldap
    config:
      base: ou=People,dc=example,dc=org
      ldap_binddn: "cn=admin,dc=example,dc=org"
      ldap_bindpw: "admin"
      ldap_uri: "ldaps://127.0.0.1"
      disable_ssl_verification: true
      person_dn_format: uid=%KEY%,ou=People,dc=example,dc=org
      additional_attributes:
        - shellentitlements
people_data_source: ldap
