---
rohittp0:
  dn: uid=rohit,ou=People,dc=ballista,dc=tech
  githubdotcomid: rohittp0
  manager: rohittp0
varshashaheen:
  dn: uid=rohit,ou=People,dc=ballista,dc=tech
  githubdotcomid: varshashaheen
  manager: rohittp0
sunithvs:
  dn: uid=rohit,ou=People,dc=ballista,dc=tech
  githubdotcomid: sunithvs
  manager: rohittp0
ajuroshan:
  dn: uid=rohit,ou=People,dc=ballista,dc=tech
  githubdotcomid: ajuroshan
  manager: rohittp0