#!/bin/bash

if [[ -z "${GITHUB_WORKSPACE}" ]]; then
  export DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
else
  export DIR="${GITHUB_WORKSPACE}"
fi

export PATH=/usr/share/rbenv/shims:$PATH
export RBENV_VERSION="$(cat "$DIR/.ruby-version")"
export LDAP_DISABLE_SSL_VERIFICATION=true

echo "===================================================================="
echo "Executing deploy-entitlements -c ${DIR}/config/entitlements.yaml" "$@"
echo "Date: $(date), Environment: entitlements-config"
echo "===================================================================="

set +e
"${DIR}/bin/deploy-entitlements" -c "${DIR}/config/entitlements.yaml" "$@" 2>&1 | grep -v "not verifying" | tee "${DIR}/deploy-output.txt"
exitcode=${PIPESTATUS[0]}
echo "exit=${exitcode}" >> "${DIR}/deploy-output.txt"

exit ${exitcode}
