name: manager

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  rubocop:
    name: runner
    runs-on: ubuntu-latest

    steps:
      - uses: ruby/setup-ruby@57d46d78b7d959dc4a248024a29bb17d4e357e5c
        with:
          ruby-version: 2.6.6
          bundler-cache: true

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: install yq
        run: sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64

      - name: bootstrap
        run: script/manager_review
